### ISSUE TITLE
Ignore Filter not applied?

### ISSUE THREAD

**Issue by julowe** [webbpinner/OpenVDMv2#14]
The 'Ignore Filter' section under 'Edit Collection System Transfer' doesn't seem to work in my instance.

Trying to ignore `._*` files and it transferred them from a Local Directory, as well as from a SSH Server. Also failed to exclude `DEPTH*` files under further testing. 

Ignore Filter strings tested include: `._*`, `._*, DEPTH*`, and `._*,DEPTH*`

Other Settings: 
Include Filter: `*`
Exclude Filter was blank
Skip files being actively written to? 
No
Skip files create/modified outside of cruise start/stop times? 
No

**Comment by webbpinner** [comment]
The filters require a leading as described would require a leading "*" ("*._*", "*DEPTH*", "*._*,*DEPTH*" ).

What's happening is the full path to the file is being passed to the filter.  The files are not being caught by the filter because of the leading path.  Give this a try and let me know how it works out.

Given that the filter is being parsed by a reasonably strict regex parser there is a chance these filter values might not work because of the leading "." which in regex syntax equates to 'any single character'.

**Comment by julowe** [comment]
Sort of got it working...

Things I tried:
Set Include filter to ```*``` and set exclude filter to

- ```"DEPTH"```
- ```"DEPTH*"```
- ```"._*"```

but all files still transferred. 

However using ```*DEPTH*,*._*``` did work - but isn't exactly what I want, e.g. it would exclude both ```DEPTH-file``` and ```file-DEPTH-name``` when I only want to exclude the first.

BUT ```[.]_*,[D]EPTH*``` does work exactly as I want. It seems the exclude call using fnmatch [(Documentation)](https://docs.python.org/2/library/fnmatch.html) needs a leading wildcard of some kind even though it doesn't say that in the docs. In fact it uses unix-style wildcards and "filenames starting with a period are not special for this module"

I assume this an outcome of your usage of fnmatch, not the function itself. But I'll leave that fun debugging to you 😄

**Comment by webbpinner** [comment]
For `*DEPTH*` please try `*/DEPTH*`.  The regex logic is applied against the full file path, not just the file name.  Adding a leading `/` before the meat of the filter criteria should only apply to filenames that start with `DEPTH`.

I appreciate that you're trying all these different filters.  Understandably I have been able to exercise the system for all possible permutations.

**Comment by julowe** [comment]
```*/DEPTH*``` does not work.

I've created a collection system transfer that just copies the directory ```docs``` from the local machine. The include filter is ```*.pdf,*.txt``` (as it has been for all previous test cases I've written about in this issue). Using the above filter in this message, OpenVDM still transfers ```docs/instrument-cals/DEPTH_paro_cal.pdf```

**Comment by webbpinner** [comment]
I built up this exact test case on the demo site and try to replicate the issue but couldn't.

Include Filter:
`*.pdf,*.txt`

Exclude Filter:
`DEPTH*`

Ignore Filter:
`*.raw`

Here are the files in the source dir:
DEPTH_paro_cal.pdf - excluded (appears on misnamed file list)
DEPTH_paro_cal.txt - excluded (appears on misnamed file list)
DEPTH_paro_cal.raw - ignored (not transferred)
file_DEPTH_paro.pdf - included (transferred)
file_DEPTH_paro.raw - ignored (not transferred)
file_DEPTH_paro.txt - included (transferred)

Please take a look at the demo site and confirm that the collection system you setup matches what you did.  Also, maybe I didn't fully understand what you are trying to accomplish.  If that's the case please explain what's different between our testing scenarios.

That said, I did find an unrelated bug where files caught by the exclude filtering were being reported twice in the mis-named files feed.  Please pull the update and apply using the ./scripts/OpenVDMv2-upgrade.sh script and restarting the OVDM_runCollectionSystemTransfers processes in Supervisor.

**Comment by webbpinner** [comment]
Here's a followup, this one excludes the file_DEPTH* regex:
Include Filter:
`.pdf,.txt`

Exclude Filter:
`*?DEPTH*`

Ignore Filter:
`*.raw`

Here are the files in the source dir:
DEPTH_paro_cal.pdf - included (transferred)
DEPTH_paro_cal.txt - included (transferred)
DEPTH_paro_cal.raw - ignored (not transferred)
file_DEPTH_paro.pdf - excluded (appears on misnamed file list)
file_DEPTH_paro.txt - excluded (appears on misnamed file list)
file_DEPTH_paro.raw - ignored (not transferred)

I was mistaken earlier regarding how the python globing works.  It's done using the [fnmatch.fnmatch](https://docs.python.org/2/library/fnmatch.html#fnmatch.fnmatch) function (which will explain why '?' is used).

**Comment by webbpinner** [comment]
Assuming this is no longer an issue. Closing ticket
