### ISSUE TITLE
Dashboard Data Directory not fully moved

### ISSUE THREAD

**Issue by julowe** [webbpinner/OpenVDMv2#15]
Tried moving 'Dashboard Data' directory from `OpenVDM/DashboardData` to `openvdm/DashboardData` and ran into web app error. (Moving the 'Transfer Logs' directory worked fine.)

If you select a different location for the 'Dashboard Data' (under the 'OpenVDM Required Directories' section) it will create the directory when you manually run 'Rebuild Cruise Directory', but it does not seem to create the manifest.json file. Manually running 'Rebuild Data Dashboard' will create the manifest.json  in the newly chosen location, but if you delete (or rename/move) the default folder (`OpenVDM/DashboardData`) the web app does not display anything beyond "An error occurred, The error has been reported." in the browser window for any page.

**Comment by webbpinner** [comment]
Removing or deleting the manifest file will "break" the dashboard but the UI should handle this in a more graceful manner.  That will need to be corrected.

I'll need to dig into the logic to figure out why the system does not switch over to using the new dashboard directory after updating the form fields.

**Comment by julowe** [comment]
Deleting manifest file does not break dashboard any more.
Successfully renamed from `OpenVDM/DashboardData`
Yay!
Tested in v2.3, [this specific commit](https://github.com/webbpinner/OpenVDMv2/commit/8974998a5a264e947850896c79d4bd8b75ebfe40)

Closing issue.
