### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by fcarvalhopacheco** [webbpinner/OpenVDMv2#20]
Hi Pinner,

Hope all is well.

I just noticed that the [this link](http://www.oceandatarat.org/?page_id=1123) is broken...

Cheers,
Fernando

**Comment by webbpinner** [comment]
Thanks for keeping me honest.  The broken link has been removed.

**Comment by fcarvalhopacheco** [comment]
All good,

Great tool, man! I was working at BIOS with R/V Atlantic explore, and we
were also using the open VDM there.

Right now, I am working with the HOT team onboard of Kilo Moana, and we are
currently discussing the options of a backup system so we can finally stop
using the VHR system (yes, believe or not). So I am trying to suggest open
VDM...

Cheers,
Fernando

**Comment by webbpinner** [comment]
Scott Ferguson (UH Director of Marine Technical Services) did show interest at the 2019 RVTEC.  You shouldn't have much issue convincing him.  Julianna on the KM has also used it (R/V Falkor) so I'm sure she'd support it.  Let me know if there's anything I can do to help.

**Comment by fcarvalhopacheco** [comment]
That's great!!!

Thanks for that. I will contact them.

Cheers,
Fernando

**Comment by fcarvalhopacheco** [comment]
Hey,

Any chance you could invite me to the slack channel? I would love to
learn new tools and help if possible.

Cheers,
Fernando
